REAP/urls.py
# from xml.etree.ElementInclude import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('frontend.urls')),
    path('profiles', include('profile_app.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.custom_page_not_found_view'

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index'),
    # xml creation
    path('insert-sample/', views.insert_sample, name='insert_sample'),
    path('insert-publication/', views.insert_publication, name='insert_publication'),
    path('add-experiment-intro/', views.add_experiment_intro, name='add_experiment_intro'),
    path('add-experiment-geolocation/', views.add_experiment_geolocation, name='add_geolocation'),
    path('add-experiment-parameters-instrument/', views.add_experiment_parameters_instrument, name='add_parameters_instrument'),
    path('add-experiment-multiple-sections/', views.add_experiment_multiple_sections, name='add_experiment_multiple_sections'),
    path('add-experiment-spectra/', views.add_experiment_spectra, name='add_experiment_spectra'),
    path('add-experiment-finish/', views.add_experiment_finish, name='add_experiment_finish'),
    # upload files
    path('upload-publication/', views.upload_publication_file, name='upload_publication'),
    path('upload-experiment/', views.upload_experiment_file, name='upload_experiment'),
    path('upload-sample/', views.upload_sample_file, name='upload_sample'),
    # clear data
    path('clear-publication-data/', views.clear_publication_data, name='clear_publication_data'),
    path('clear-sample-data/', views.clear_sample_data, name='clear_sample_data'),
    path('clear-experiment-data/', views.clear_experiment_data, name='clear_experiment_data'),
    # delete session
    path('delete-experiment-intro/', views.delete_experiment_intro, name='delete_experiment_intro'),
    path('delete-experiment-geolocation/', views.delete_experiment_geolocation, name='delete_experiment_geolocation'),
    path('delete-experiment-parameter-instrument/', views.delete_experiment_parameters_instrument, name='delete_experiment_parameters_instrument'),
    path('delete-experiment-multiple-sections/', views.delete_experiment_multiple_sections, name='delete_experiment_multiple_sections'),
    path('delete-experiment-spectra/', views.delete_experiment_spectra, name='delete_experiment_spectra'),
    # ad hoc
    path('contact/', views.contact, name='contact'),
    # path('insert-experiment/', views.insert_experiment, name='insert_experiment'),
]

frontend/models.py
from django.db import models


class Samples(models.Model):
    """
    Model to keep records of samples
    """
    
    sample_uid = models.CharField(max_length=50, default="")
    sample_name = models.CharField(max_length=50, default="")


class Publications(models.Model):
    """
    Model to keep records of publications
    """

    publications_uid = models.CharField(max_length=50, default="")
    publication_title = models.CharField(max_length=50, default="")

frontend/views.py
from dataclasses import asdict
import json
from profile_app.models import Profile
from .functions import handle_uploaded_experiment_file, handle_uploaded_publication_file, handle_uploaded_file, handle_bibtex
from django.shortcuts import render, redirect, get_object_or_404
from .models import Samples, Publications
from .forms import ContactForm, InsertSampleForm, InsertPublicationForm, UploadFileForm
from .forms import ExperimentGeolocation, ExperimentMultipleSections, ExperimentIntro, ExperimentParameterInstrument
from .forms import ExperimentSpectra
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from xml_parser.xml_parsers import generateXMLPublication, generateXMLSample, generateXMLExperiment
from django.http.response import JsonResponse



@login_required
def insert_sample(request):
    """ 
    A view to return the insert sample page 
    From input it constructs the dictionary needed for the xml parser
    """

    user_profile = get_object_or_404(Profile, user=request.user)

    # if not 'sample_added_fields' in request.session:
    #     request.session['sample_added_fields'] = []

    template = 'frontend/insert_sample.html'

    if request.method == 'GET':
        request.session['sample_added_fields'] = []
        session = request.session['sample_added_fields']
        form = InsertSampleForm(session=session)
    else:
        session = request.session['sample_added_fields']
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = json.load(request)
            ajax_session = data.get('session')
            request.session['sample_added_fields'] = ajax_session
            return JsonResponse({'status': ajax_session})
        else:
            form = InsertSampleForm(request.POST, session=session)
            if form.is_valid():
            
                input_dict = {}

                keys = []
                for i in range(1, len(form.fields)+1):
                    keys.append(i)

                values = []
                for field in form:

                    array = []
                    array.append(field.name[0:field.name.index("_x")])
                    array.append(field.name[field.name.index("x_")+2:])

                    if 'auto_fill' in field.field.widget.attrs and len(form.cleaned_data[field.name]) == 0:
                        array.append(field.field.widget.attrs['auto_fill'])
                    else:
                        array.append(form.cleaned_data[field.name])
                    values.append(array)

                    if array[0] == "sample" and array[1] == "uid":
                        print(Samples.objects.all())
                        # if not Samples.objects.get(sample_uid=array[2]).exists():
                        #     Samples.objects.create(sample_uid=array[2])
                    #if array[0] == "sample" and array[1] == "name":

                # keys and values are inserted in dict
                for i in range(len(keys)):
                    input_dict[keys[i]] = values[i]

                request.session['sample_added_fields'] = []
                session = []
                
                generateXMLSample("xml_sample.xml", input_dict)
                
                messages.success(request, 'Your data has been inserted!')

            else:
                messages.error(
                    request, "Please correct any errors")
                return render(request, template, {'form': form})

    if 'uploaded_sample_data' in request.session:
        if request.session['uploaded_sample_data'] != None:
            uploaded_data = request.session['uploaded_sample_data']
        else:
            uploaded_data = None
    else:
        uploaded_data = None

    session_list = []
    for s in session:
        session_list.append(s)

    # user_profile = get_object_or_404(Profile, user=request.user)

    context = {
        'uploaded_data': json.dumps(uploaded_data),
        'form': form,
        'profile': user_profile,
        'session_json': json.dumps(session_list),
    }

    return render(request, template, context)


@login_required
def insert_publication(request):
    """ 
    A view to return the insert experiment page 
    From input it constructs the dictionary needed for the xml parser
    """

    user_profile = get_object_or_404(Profile, user=request.user)

    # if not 'publication_added_fields' in request.session:
    #     request.session['publication_added_fields'] = []

    template = 'frontend/insert_publication.html'
    # session = request.session['publication_added_fields']

    if request.method == 'GET':
        request.session['publication_added_fields'] = []
        session = request.session['publication_added_fields']
        form = InsertPublicationForm(session=session)
    else:
        session = request.session['publication_added_fields']
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = json.load(request)
            ajax_session = data.get('session')
            request.session['publication_added_fields'] = ajax_session
            return JsonResponse({'status': ajax_session})
        else:
            form = InsertPublicationForm(request.POST, session=session)
            if form.is_valid():
                

                input_dict = {}

                keys = []
                for i in range(1, len(form.fields)+1):
                    keys.append(i)

                values = []
                for field in form:
                    array = []
                    array.append(field.name[0:field.name.index("_x")])
                    array.append(field.name[field.name.index("x_")+2:])

                    if 'auto_fill' in field.field.widget.attrs and len(form.cleaned_data[field.name]) == 0:
                        array.append(field.field.widget.attrs['auto_fill'])
                    else:
                        array.append(form.cleaned_data[field.name])
                    values.append(array)
                # keys and values are inserted in dict
                for i in range(len(keys)):
                    input_dict[keys[i]] = values[i]

                request.session['publication_added_fields'] = []
                session = []

                generateXMLPublication("xml_publication.xml", input_dict)
                
                messages.success(request, 'Your data has been inserted!')

            else:
                messages.error(
                    request, "Please correct any errors")
                return render(request, template, {'form': form})

    if 'uploaded_experiment_data' in request.session:
        if request.session['uploaded_experiment_data'] != None:
            uploaded_data = request.session['uploaded_experiment_data']
        else:
            uploaded_data = None
    else:
        uploaded_data = None
    
    session_list = []
    for s in session:
        session_list.append(s)

    context = {
        'uploaded_data': json.dumps(uploaded_data),
        'form': form,
        'profile': user_profile,
        'session_json': json.dumps(session_list),
    }

    return render(request, template, context)


@login_required
def add_experiment_intro(request):
    
    user_profile = get_object_or_404(Profile, user=request.user)
    
    if not 'experiment_add_intro' in request.session:
        request.session['experiment_add_intro'] = []

    template = 'frontend/add_experiment_intro.html'
    session = request.session['experiment_add_intro']

    if request.method == 'GET':
        request.session['experiment_add_intro'] = []
        form = ExperimentIntro(session=session)
    else:
        session = request.session['experiment_add_intro']
        print(session)
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = json.load(request)
            ajax_session = data.get('session')
            request.session['experiment_add_intro'] = ajax_session
            return JsonResponse({'status': ajax_session})
        else:
            form = ExperimentIntro(request.POST, session=session)
            if form.is_valid():
                
                # creates the dictionary
                input_dict = {}
                # creates an array of the keys to be used in dict
                keys = []
                for i in range(1, len(form.fields)+1):
                    keys.append(i)
                # creates an array of arrays for the dict
                # each array includes parent_tag, name of tag, and content
                # if there is an autofill attribute, then autofill content will be used,
                # unless field has been altered by researcher
                values = []
                for field in form:
                    array = []
                    array.append(field.name[0:field.name.index("_x")])
                    array.append(field.name[field.name.index("x_")+2:])

                    if 'auto_fill' in field.field.widget.attrs and len(form.cleaned_data[field.name]) == 0:
                        array.append(field.field.widget.attrs['auto_fill'])
                    else:
                        array.append(form.cleaned_data[field.name])
                    values.append(array)
                # keys and values are inserted in dict
                for i in range(len(keys)):
                    input_dict[keys[i]] = values[i]
                request.session['posted_experiment_intro'] = input_dict
                request.session['experiment_add_intro'] = []
                session = []
                
                messages.success(request, 'Your data has been inserted!')

            else:
                messages.error(
                    request, "Please correct any errors")

frontend/templates/frontend/about.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">

<h1>About</h1>

</div>
{% endblock %}

frontend/templates/frontend/add_experiment_finish.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h1 class="h1 mx-auto rounded contact-heading">
                Add Experiment Finish
            </h1>
        </div>
    </div>

    <div class="row text-center">
        <ul class="list-group list-group-horizontal mx-auto">
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_experiment_intro' %}">Intro</a>
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_geolocation' %}">Geolocation</a>
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_parameters_instrument' %}">Parameters Instrument</a>
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_experiment_multiple_sections' %}">Multiple Sections</a>
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_experiment_spectra' %}">Spectra</a>
            <li class="list-group-item bg-primary text-white">Finish</li>
        </ul> 
    </div>

    <div class="row mx-auto my-5 text-center">
        <div class="col-6 text-center">
            <h2 class="h2 my-5">Experiment Intro</h2>
            <table class="table mx-auto border border-light">
                <tr>
                  <th scope="col-3">Number</th>
                  <th scope="col-3">Field name</th>
                  <th scope="col-3">Input</th>
                </tr>
                
                {% for key, value in experiment_intro.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
            
        <div class="col-6 text-center">
            <h2 class="h2 my-5">Geolocation</h2>
            <table class="table mx-auto border border-light">
                <tr>
                  <th scope="col-3">Number</th>
                  <th scope="col-3">Field name</th>
                  <th scope="col-3">Input</th>
                </tr>
            
                {% for key, value in experiment_geolocation.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    
    <div class="row mx-auto my-5 text-center">
        <div class="col-6 text-center">
            <h2 class="h2 my-5">Parameter Instruments</h2>

            <table class="table mx-auto border border-light">
                <tr>
                  <th scope="col-3">Number</th>
                  <th scope="col-3">Field name</th>
                  <th scope="col-3">Input</th>
                </tr>

                {% for key, value in experiment_parameters_instrument.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <div class="col-6 text-center">
            <h2 class="h2 my-5">Multiple Sections</h2>
            <table class="table mx-auto border border-light">
                <tr>
                  <th scope="col-3">Number</th>
                  <th scope="col-3">Field name</th>
                  <th scope="col-3">Input</th>
                </tr>
                {% for key, value in experiment_multiple_sections.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

    </div>

            
    <div class="row my-5 mx-auto">
        
            
        <div class="col-6 text-center">
            <h2 class="h2 my-5">Spectra</h2>
            <table class="table mx-auto border border-light">
                
                <tr>
                  <th scope="col">Number</th>
                  <th scope="col">Field name</th>
                  <th scope="col">Input</th>
                </tr>
                {% for key, value in experiment_add_spectra.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="row my-5 mx-auto">
        <div class="col text-center">
            <h2 class="h2 my-5">Full Input</h2>
            <table class="table mx-auto border border-light">
                <tr>
                  <th scope="col">Number</th>
                  <th scope="col">Field name</th>
                  <th scope="col">Input</th>
                </tr>
                {% for key, value in input_dict.items %}
                <tr>
                    <th scope="row">{{ key }}</th>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
            
    </div>
            
    <div class="row my-5">
    <form class="col text-center mx-auto my-5" method="POST" action="{% url 'frontend:add_experiment_finish' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">
            Create XML file
        </button>
    </form>
    </div>

</div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
<script>

</script>
{% endblock %}

frontend/templates/frontend/add_experiment_geolocation.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">

        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h1 class="h1 mx-auto rounded contact-heading">
                Add Geolocation
            </h1>
        </div>
    </div>

    <div class="row text-center">
        <ul class="list-group list-group-horizontal mx-auto">
            <a class="list-group-item bg-success text-white" href="{% url 'frontend:add_experiment_intro' %}">Intro</a>
            <li class="list-group-item bg-primary text-white" href="{% url 'frontend:add_geolocation' %}">Geolocation</li>
            <a class="list-group-item" href="{% url 'frontend:add_parameters_instrument' %}">Parameters Instrument</a>
            <a class="list-group-item" href="{% url 'frontend:add_experiment_multiple_sections' %}">Multiple Sections</a>
            <a class="list-group-item" href="{% url 'frontend:add_experiment_spectra' %}">Spectra</a>
            <a class="list-group-item" href="{% url 'frontend:add_experiment_finish' %}">Finish</a>
        </ul> 
    </div>

    <!-- <div class="row text-center my-5">
        <div class="col mx-auto">
            <a class="btn btn-danger" href="{% url 'frontend:upload_sample' %}">Upload Sample</a>
        </div>
    </div> -->

    <div class="row">
        <div class="col-10 mx-auto mt-3 mb-5 p-4 first-div border rounded">
            <form method="post" id="form">
                {% csrf_token %}
                {{ form.body_x_uid|as_crispy_field }}
                {{ form.body_x_coordinate_system|as_crispy_field }}
                <div id="geolocations">
                    <div id="geolocation">
                        <a class="btn btn-primary mx-3 mb-4" data-toggle="collapse" href="#collapseGeolocation" role="button"
                            aria-expanded="false" aria-controls="collapseGeolocation">Geolocation</a>
                        <div class="collapse" id="collapseGeolocation">
                        <div class="card card-body mb-3 border border-black">
                            {{ form.geolocation_x_place|as_crispy_field }}
                            {{ form.geolocation_x_region|as_crispy_field }}
                            {{ form.geolocation_x_country_code|as_crispy_field }}
                            {{ form.geolocation_x_type|as_crispy_field }}
                            <p class="lead">Coordinates</p>
                            <div class="card card-body mb-3">
                                <p>Coordinate</p>
                                <div id="coordinates">
                                    <div id="coordinate">
                                        <div class="card card-body mb-3 border border-black">
                                            {{ form.coordinate_x_latitude|as_crispy_field }}
                                            {{ form.coordinate_x_longitude|as_crispy_field }}
                                            {{ form.coordinate_x_altitude|as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <btn class="btn btn-success mx-auto addfields_button" parent="coordinates" child="coordinate" onclick="addFields(event)"><i class="fa fa-plus" aria-hidden="true"></i></btn>
                                    <btn class="btn btn-danger mx-auto removefields_hover removefields_button" id="remove_coordinates" parent="coordinates" onclick="removeFields(event)"><i class="fa fa-trash" aria-hidden="true"></i></btn>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>

                <div class="row my-3">
                    <btn class="btn btn-success mx-auto addfields_button" parent="geolocations" child="geolocation" onclick="addFields(event)"><i class="fa fa-plus" aria-hidden="true"></i></btn>
                    <btn class="btn btn-danger mx-auto removefields_hover removefields_button" id="remove_geolocations" parent="geolocations" onclick="removeFields(event)"><i class="fa fa-trash" aria-hidden="true"></i></btn>
                </div>
                
                {% if done %}
                <input class="my-2" type="submit" value="Update section"/>
                {% else %}
                <input class="my-2" type="submit" value="Attach Intro to file"/>
                {% endif %}
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
<script>
    var uploaded_data = '{{ uploaded_data|safe }}';
    var researcher = '{{ profile.experimentalist_uid }}';
    var sessionArray = '{{session_json|safe}}';

    let originalGeolocation = document.getElementById("geolocation");
    let originalCoordinate = document.getElementById("coordinate");

    const globalClones = [
    originalGeolocation.cloneNode(true),
    originalCoordinate.cloneNode(true)
    ];

    let ajaxURL = "/add-experiment-geolocation/";
</script>
<script type="text/javascript" src="{% static 'frontend/js/add_form_fields.js' %}"></script>  
{% endblock %}

frontend/templates/frontend/contact.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h1 class="h1 mx-auto rounded contact-heading">
                Contact
            </h1>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-10 mx-auto">
            <p class="text-center">Feel free to send us a message.</p>
            <p class="text-center">We will happily respond to any feedback, comments, ideas, or any other inquiries you may have.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-10 col-md-5 mx-auto mt-3 mb-5 p-4 first-div border rounded">
            <form id="form" method="post">

                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn contact-btn m-4" data-toggle="modal" data-target="message"
                    type="submit">Send</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

frontend/templates/frontend/index.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="row">
    <div id="hero-background" aria-label="Abstract picture of a city view. White background, grey and black building">

        <div class="row mb-5 cover-text">
            <div class="col-10 pt-5 pb-3 mx-auto text-white">
                <h1 class="h1 pt-4 text-center">
                    REAP
                    <hr>
                </h1>
                <h2 class="lead text-center">Database Fun</h2>
            </div>
        </div>

        {% if user.is_authenticated %}

        <div class="row cover-text">

            <div class="col-4 col-md-5 col-lg-3 my-2 mx-auto text-center text-white border border-white rounded animation first-div hover">
                <a href="{% url 'frontend:insert_publication' %}">
                    <h2 class="text-white">PUBLICATION</h2>
                </a>
            </div>

            <div class="col-4 col-md-5 col-lg-3 my-2 mx-auto text-center text-white border border-white rounded animation second-div hover">
                <a href="{% url 'frontend:add_experiment_intro' %}">
                    <h2 class="text-white">EXPERIMENT</h2>
                </a>
            </div>

            <div class="col-4 col-md-5 col-lg-3 my-2 mx-auto text-center text-white border border-white rounded animation third-div hover">
                <a href="{% url 'frontend:insert_sample' %}">
                    <h2 class="text-white">SAMPLE</h2>
                </a>
            </div>

        </div>

        {% else %}

        <div class="row cover-text">

            <div class="col-8 col-md-5 col-lg-3 my-2 mx-auto text-center text-white border border-white rounded animation third-div hover">
                <a href="{% url 'account_login' %}">
                    <h2 class="text-white">LOGIN</h2>
                </a>
            </div>
            
            <div class="col-8 col-md-5 col-lg-3 my-2 mx-auto text-center text-white border border-white rounded animation first-div hover">
                <a href="{% url 'account_signup' %}">
                    <h2 class="text-white">REGISTER</h2>
                </a>
            </div>

        </div>

        {% endif %}

    </div>
</div>

<div class="row">
    <div class="col-12 mx-auto text-center text-white p-5 index-intro">
        <h3 class="h3 my-5">WE'LL MAKE IT EASY TO GET STUFF DONE</h3>
        <h3 class="h3">YOU'LL SEE!</h3>
        <h3 class="h3 my-5">IT'S GONNA BE FANTASTIC!</h3>
        <h3 class="h3 my-5">SIGN UP AND INTERACT WITH OUR PARSER</h3>
    </div>
</div>

<div class="row">
    <a class="col-6 border border-white intro-content position-relative first-div" href="{% url 'frontend:contact' %}">
        <h3 class="h3 text-white centered">Contact</h3>
    </a>
    <a class="col-6 border border-white text-dark intro-content position-relative fourth-div" href="#">
        <h3 class="h3 centered">About</h3>
    </a>
</div>

</div>

{% endblock %}

frontend/templates/frontend/insert_data.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h1 class="h1 mx-auto rounded contact-heading">
                Insert Data
            </h1>
        </div>
    </div>

    <div class="row mb-3 text-center">
        <a class="col-3 mx-auto border border-black" href="{% url 'frontend:insert_sample' %}">
            <div>
                Sample
            </div>
        </a>

        <a class="col-3 mx-auto border border-black" href="{% url 'frontend:insert_experiment' %}">
            <div>
                Experiment
            </div>
        </a>

        <a class="col-3 mx-auto border border-black" href="{% url 'frontend:insert_publication' %}">
            <div>
                Publication
            </div>
        </a>
    </div>

</div>
{% endblock %}

frontend/templates/frontend/upload_experiment.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="container-header"></div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">

        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h1 class="h1 mx-auto rounded contact-heading">
                Insert XML file of experiment
            </h1>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-10 mx-auto">
            <p class="text-center">Upload an XML file</p>
            <p class="text-center">Text content will be passed into the form</p>
        </div>
    </div>

    <div class="row">
        <div class="col-10 col-md-5 mx-auto mt-3 mb-5 p-4 first-div border rounded">
            <form id="form" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn contact-btn m-4" data-toggle="modal" data-target="message"
                    type="submit">Send</button>

            </form>
        </div>

    </div>

</div>
</div>
{% endblock %}