REAP/urls.py
# from xml.etree.ElementInclude import include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('frontend.urls')),
    path('profiles', include('profile_app.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.custom_page_not_found_view'

profile_app/urls.py
from django.urls import path
from . import views

app_name = 'profile_app'

urlpatterns = [
    path('', views.profile, name='profiles'),
    path('update-user/', views.UpdateUser.as_view(), name="update_user"),
    path('<int:pk>/update/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('password/', views.PasswordChangeView.as_view(), name='password'),
]

profile_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    """
    Profile model to keep track of paid status and order history
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    experimentalist_uid = models.CharField(max_length=50, default="")
    laboratory_uid = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile
    """
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

profile_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from .models import Profile


class UserForm(UserChangeForm):
    """View and edit user"""
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        """Meta class"""
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            )


# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['experimentalist_uid']

class ProfileForm(forms.Form):
    """
    Form to update profil's information
    """
    experimentalist_uid = forms.CharField(required=False)

profile_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from allauth.account.views import PasswordChangeView, PasswordResetView
from django.views.generic.edit import UpdateView
from django.contrib import messages
from django.views import generic
from .models import Profile
from .forms import UserForm, ProfileForm
from django.http import HttpResponseRedirect


@login_required
def profile(request):
    """
    A view to return the profile page
    Premium membership in context in order to provide link in template,
    in case admin deletes and create a new => new id for product
    """
    user_profile = get_object_or_404(Profile, user=request.user)

    template = 'profile_app/profiles.html'
    context = {
        'profile': user_profile,
    }

    return render(request, template, context)


class UpdateUser(SuccessMessageMixin, generic.UpdateView):
    """
    View to update user profile
    """
    form_class = UserForm
    template_name = 'profile_app/update_user.html'
    success_message = 'Profile updated successfully!'
    success_url = '/profiles'

    def get_object(self):
        return self.request.user


class UpdateProfileView(UpdateView):
    """
    User can update comment here
    """
    model = Profile
    fields = ['experimentalist_uid', 'laboratory_uid']
    template_name_suffix = '_update_profile'
    success_url = '/profiles'

profile_app/templates/profile_app/profile_update_profile.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row my-5">
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">
            <div class="col-10 py-5 pb-2 mx-auto text-center">
                <h1 class="h1 mx-auto rounded contact-heading">
                    Update Profile
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-10 col-md-5 mx-auto mt-3 mb-5 p-4 first-div border rounded">
              <form id="form" method="post" class="mt-3">
          
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn update-prof-btn text-white my-3" data-toggle="modal" data-target="message" type="submit">Save</button>
          
              </form>
            </div>
          
          </div>
    </div>
{% endblock %}

profile_app/templates/profile_app/profiles.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="container-header"></div>
    </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row position-relative">
        <div class="col-12 pt-5 text-center title-height">
            <h2 class="h2 p-3 centered border rouded" id="profile-heading">PROFILE</h2>
        </div>
        <hr>
    </div>



    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <h2 class="h2 mx-auto">Welcome to your profile, {{ profile.user }}</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <a class="h2 border border-black mx-auto p-2" href="{% url 'profile_app:update_profile' profile.id %}">Update Profile info</a>
        </div>
    </div>

    <div class="row">
        <div class="col-10 py-5 pb-2 mx-auto text-center">
            <a class="h2 border border-black mx-auto p-2" href="{% url 'profile_app:update_user' %}">Update user info</a>
        </div>
    </div>
</div>
{% endblock %}

profile_app/templates/profile_app/update_user.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row my-5">
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">
            <div class="col-10 py-5 pb-2 mx-auto text-center">
                <h1 class="h1 mx-auto rounded contact-heading">
                    Update User
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-10 col-md-5 mx-auto mt-3 mb-5 p-4 first-div border rounded">
              <form id="form" method="post" class="mt-3">
          
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn update-prof-btn text-white my-3" data-toggle="modal" data-target="message" type="submit">Save</button>
          
              </form>
            </div>
          
          </div>
    </div>
{% endblock %}